src/Entity/GroupePrive.php
<?php

namespace App\Entity;

use App\Repository\GroupePriveRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GroupePriveRepository::class)]
#[UniqueEntity(fields: ['nom', 'chefGroupe'], message: 'Ce nom de groupe n\'est pas disponible')]
class GroupePrive
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 55)]
    #[Assert\NotBlank(message: 'Vous devez indiquer un nom de groupe')]
    private ?string $nom = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'groupesPrives')]
    private Collection $user;

    /**
     * @var Collection<int, Sortie>
     */
    #[ORM\OneToMany(targetEntity: Sortie::class, mappedBy: 'groupePrive')]
    private Collection $sortie;


    #[ORM\ManyToOne(targetEntity: User::class)]
    private ?User $chefGroupe = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->sortie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function setUser(iterable $users): static
    {
        $this->user->clear();
        foreach ($users as $user) {
            $this->addUser($user);
        }

        return $this;
    }


    public function removeUser(User $user): static
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortie(): Collection
    {
        return $this->sortie;
    }

    public function addSortie(Sortie $sortie): static
    {
        if (!$this->sortie->contains($sortie)) {
            $this->sortie->add($sortie);
            $sortie->setGroupePrive($this);
        }

        return $this;
    }

    public function removeSortie(Sortie $sortie): static
    {
        if ($this->sortie->removeElement($sortie)) {
            // set the owning side to null (unless already changed)
            if ($sortie->getGroupePrive() === $this) {
                $sortie->setGroupePrive(null);
            }
        }

        return $this;
    }

    public function getChefGroupe(): ?User
    {
        return $this->chefGroupe;
    }

    public function setChefGroupe(?User $chefGroupe): self
    {
        $this->chefGroupe = $chefGroupe;
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Sortie;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'L\'email est déjà utilisé')]
#[UniqueEntity(fields: ['pseudo'], message: 'Le pseudo n\'est pas disponible')]
#[UniqueEntity(fields: ['telephone'], message: 'Le téléphone n\'est pas disponible')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: "L'email est obligatoire")]
    #[Assert\Email(message: "L'adresse email n'est pas valide")]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9._%+-]+@campus-eni\.fr$/',
        message: "L'email doit se terminer par @campus-eni.fr"
    )]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank(
        message: "Le mot de passe est obligatoire",
        groups: ['enregistrement']
    )]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "Le nom est obligatoire")]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "Le prénom est obligatoire")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $confirmationToken = null;


    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private bool $profileCompleted = false;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 50, unique: true, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(type: 'boolean', options: ['default' => true])]
    private bool $isActif = true;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Site $site = null;

    /**
     * @var Collection<int, Sortie>
     */
    #[ORM\ManyToMany(targetEntity: Sortie::class, mappedBy: 'users')]
    private Collection $sorties;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $photo = null;

    /**
     * @var Collection<int, GroupePrive>
     */
    #[ORM\ManyToMany(targetEntity: GroupePrive::class, mappedBy: 'user')]
    private Collection $groupesPrives;


    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
        $this->groupesPrives = new ArrayCollection();
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): static
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }

    public function isProfileCompleted(): bool
    {
        return $this->profileCompleted;
    }

    public function setProfileCompleted(bool $profileCompleted): static
    {
        $this->profileCompleted = $profileCompleted;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function isActif(): bool
    {
        return $this->isActif;
    }

    public function setIsActif(bool $isActif): static
    {
        $this->isActif = $isActif;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): static
    {
        $this->site = $site;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSortie(Sortie $sortie): static
    {
        if (!$this->sorties->contains($sortie)) {
            $this->sorties->add($sortie);
            $sortie->addUser($this);
        }

        return $this;
    }


    public function removeSortie(Sortie $sortie): static
    {
        if ($this->sorties->removeElement($sortie)) {
            $sortie->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, GroupePrive>
     */
    public function getGroupesPrives(): Collection
    {
        return $this->groupesPrives;
    }

    public function addGroupePrive(GroupePrive $groupe): static
    {
        if (!$this->groupesPrives->contains($groupe)) {
            $this->groupesPrives->add($groupe);
            $groupe->addUser($this);
        }

        return $this;
    }

    public function removeGroupePrive(GroupePrive $groupe): static
    {
        if ($this->groupesPrives->contains($groupe)) {
            $this->groupesPrives->removeElement($groupe);
            $groupe->removeUser($this);
        }

        return $this;
    }

    public function getNomComplet(): string
    {
        return $this->getNom() . ' ' . $this->getPrenom() . ' (' . $this->getPseudo() . ')';
    }
}

src/Form/GroupePriveType.php
<?php

namespace App\Form;

use App\Entity\GroupePrive;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GroupePriveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom du groupe privé',
                'required' => true,
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => fn(User $user) => $user->getNomComplet(),
                'label' => 'Membres à ajouter : ',
                'multiple' => true,
                'expanded' => false,
                'query_builder' => function (UserRepository $repo) use ($options) {
                    $groupe = $options['data'];

                    $excluded = [];
                    if ($groupe && $groupe->getChefGroupe()) {
                        $excluded[] = $groupe->getChefGroupe()->getId();
                    }

                    $qb = $repo->createQueryBuilder('u');
                    if (!empty($excluded)) {
                        $qb->where($qb->expr()->notIn('u.id', ':excluded'))
                            ->setParameter('excluded', $excluded);
                    }

                    return $qb->orderBy('u.nom', 'ASC');
                },
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => GroupePrive::class,
        ]);
    }
}

src/Controller/GroupePriveController.php
<?php

namespace App\Controller;

use App\Entity\GroupePrive;
use App\Entity\User;
use App\Form\GroupePriveType;
use App\Repository\GroupePriveRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/groupe-prive', name: 'groupe_prive')]
final class GroupePriveController extends AbstractController
{
    #[IsGranted('ROLE_USER')]
    #[Route('/', name: '')]
    public function index(Request $request, GroupePriveRepository $groupePriveRepository): Response
    {
        $user = $this->getUser();
        $groupePrives = $groupePriveRepository->findByChef($user);

        return $this->render('groupe_prive/index.html.twig', [
            'user' => $user,
            'groupePrives' => $groupePrives,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/edit', name: '_nouveau', methods: ['GET', 'POST'])]
    public function nouveauGroupePrive(Request $request, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();

        $groupe = new GroupePrive();
        $groupe->setChefGroupe($user);
        $form = $this->createForm(GroupePriveType::class, $groupe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($groupe);
            $em->flush();

            $this->addFlash('success', 'Groupe privé créé avec succès.');

            return $this->redirectToRoute('groupe_prive');
        }

        return $this->render('groupe_prive/edit.html.twig', [
            'groupeprive_form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/update/{id}', name: '_gerer', methods: ['GET', 'POST'])]
    public function gererGroupePrive(GroupePrive $groupePrive, Request $request, EntityManagerInterface $em): Response
    {

        $form = $this->createForm(GroupePriveType::class, $groupePrive);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->flush();
            $this->addFlash('success', 'Groupe modifié avec succès.');

            return $this->redirectToRoute('groupe_prive');

        }


        return $this->render('groupe_prive/manage_members.html.twig', [
            'groupePrive' => $groupePrive,
            'groupeprive_form' => $form->createView(),
        ]);
    }

}

templates/groupe_prive/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer groupe{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-8">

            <h1>Créer un groupe privé</h1>

            {{ form_start(groupeprive_form) }}
            {{ form_row(groupeprive_form.nom) }}
            {{ form_row(groupeprive_form.user, {'attr': {'class': 'select2'}}) }}

            <button type="submit" name="submit_groupe_prive" class="btn btn-success">Créer</button>
            <button type="button" onclick="window.location.href='{{ path('groupe_prive') }}'" class="btn btn-secondary">Retour</button>
            {{ form_end(groupeprive_form) }}


        </div>
    </div>


{% endblock %}

templates/groupe_prive/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes groupes{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-8">

            <h1>Mes groupes</h1>
            <div class="row">
                <button type="button" class="btnAdd"
                        onclick="window.location.href='{{ path('groupe_prive_nouveau') }}'">
                    Créer
                </button>
                {% for groupePrive in groupePrives %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ groupePrive.nom }}</h5>

                                <p><strong>Chef du groupe :</strong>
                                    {% if groupePrive.chefGroupe %}
                                        {{ groupePrive.chefGroupe.nom }} {{ groupePrive.chefGroupe.prenom }}
                                    {% else %}
                                        <em>Non défini</em>
                                    {% endif %}
                                </p>

                                <p><strong>Membres :</strong></p>
                                <div>
                                    {% for user in groupePrive.user %}
                                        <p>{{ user.nom }} {{ user.prenom }}</p>
                                    {% else %}
                                        <p><em>Aucun membre</em></p>
                                    {% endfor %}
                                </div>

                                <button type="button"
                                        onclick="window.location.href='{{ path('groupe_prive_gerer', { id: groupePrive.id }) }}'"
                                        class="btnMod">
                                    Gérer le groupe
                                </button>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p>Aucun groupe privé trouvé.</p>
                {% endfor %}

            </div>

        </div>
    </div>
{% endblock %}

templates/groupe_prive/manage_members.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier groupe{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-8">

            <h1>Modifier ce groupe privé : {{ groupePrive.nom }}</h1>
            <div class="">
                <strong>Membres présents :</strong>
                {% for user in groupePrive.user %}
                    <div> {{ user.nomComplet }} </div>
                {% else %}
                    <p>Aucun membre</p>
                {% endfor %}
            </div>
            <div>
                {{ form_start(groupeprive_form) }}

                {{ form_row(groupeprive_form.user, {'attr': {'class': 'select2'}}) }}

                <button type="submit" name="submit_groupe_prive_update" class="btn btn-success">Modifier</button>
                <button type="button" onclick="window.location.href='{{ path('groupe_prive') }}'" class="btn btn-secondary">Retour</button>
                {{ form_widget(groupeprive_form.nom, {'attr':{'hidden' : true} }) }}

                {{ form_end(groupeprive_form) }}

            </div>
        </div>
    </div>


{% endblock %}